project:
  type: website
  output-dir: docs

website:
  title: "Jonathan Lindbloom"
  navbar:
    search: false
    left:
      # - href: about.qmd
      #   text: Home
      - research.qmd
      - blog.qmd
  # twitter-card:
  #   creator: "@qed404"
  #   site: "@qed404"
  #

format:
  html:
    theme: 
      - superhero
      - custom.scss
    css: styles.css
    toc: true


