project:
  type: website
  output-dir: main

website:
  title: "Jonathan Lindbloom"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - blog.qmd
  # twitter-card:
  #   creator: "@qed404"
  #   site: "@qed404"
  #

format:
  html:
    theme: 
      - superhero
      - custom.scss
    css: styles.css
    toc: true


