project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!misc/"
    - "!talk_slides/"

website:
  title: "Jonathan Lindbloom"
  google-analytics: "G-QH680DR4M4"
  navbar:
    search: false
    left:
      # - href: about.qmd
      #   text: Home
      - text: "CV"
        href: https://drive.google.com/file/d/1wTx_4NKpi4keg35xnoAQ30eU275eSUET/view?usp=sharing
      - research.qmd
      - teaching.qmd
      #- office_hours.qmd
      - software.qmd
      #- blog.qmd
  # twitter-card:
  #   creator: "@qed404"
  #   site: "@qed404"
  #

format:
  html:
    theme: 
      - superhero
      - custom.scss
    css: styles.css
    toc: true
    linkcolor: "#00ccff"


