---
title: "Teaching"
echo: false
jupyter: python3
section-divs: false
keep-md: true
---

This page summarizes my teaching activities. 

## Instructor

- **\*\*Upcoming\*\*** [Math 56: Computational and Experimental Mathematics](https://math.dartmouth.edu/~m56w25/), Dartmouth College, Winter 2025
- [Math 3: Calculus](https://math.dartmouth.edu/~m3f23/general.phtml), Dartmouth College, Fall 2023 [[lecture notes]](https://nbviewer.org/github/jlindbloom/jlindbloom.github.io/blob/main/documents/m3f23_notes.pdf)


## Teaching assistant

- [Math 22: Linear Algebra and Applications](https://math.dartmouth.edu/~m22s23/), Dartmouth College, Spring 2023
- [Math 56: Computational and Experimental Mathematics](https://math.dartmouth.edu/~m56w23/), Dartmouth College, Winter 2023
- [Math 3: Calculus](https://math.dartmouth.edu/~m3w23/), Dartmouth College, Winter 2023
- [Math 3: Calculus](https://math.dartmouth.edu/~m3w22/), Dartmouth College, Winter 2022
- [Math 3: Calculus](https://canvas.dartmouth.edu/courses/48609), Dartmouth College, Fall 2021

<!-- 
## Grading Assistant
- Math 3311: Introduction to Proofs and Analysis, Southern Methodist University, Fall 2020 / Spring 2021
- Math 3304: Introduction to Linear Algebra, Southern Methodist University, Fall 2019 / Spring 2020 / Fall 2020
- Math 1337: Calculus I, Southern Methodist University, Fall 2018 -->



## Directed reading programs

I have enjoyed participating as a mentor in Dartmouth's [Directed Reading Program (DRP)](https://math.dartmouth.edu/~drp/) for undergraduates. Past reading programs I have supervised include:


- Markov Chain Monte Carlo and Bayesian Computation (Spring 2024, with Michael Bond and Vadin Thadhani)
- Computational Measure Transport (Winter 2024, with William O'Brien and Paul Chirkov)
<!-- - A Tour of the Finite Element Method (Winter 2024) -->
- Markov Chain Monte Carlo and Bayesian Computation (Spring 2023, with Daniel Carstensen)
- Bayesian Modeling and Computation (Spring 2022, with Ivy Yan)
- Nonlinear Dynamics, Chaos, and Ergodicity (Fall 2021, with Andrew White)

If you are interested in participating in a DRP (formally or informally), feel free to write me via email [here](mailto:jonathan.t.lindbloom.gr@dartmouth.edu).

<!-- <details>
<summary>How do I dropdown?</summary>
<br>
This is how you dropdown.
</details> -->



## Miscellaneous lecture notes and slides

- Overview of regularization parameter selection methods [ [Slides] ](https://drive.google.com/file/d/1TWQOOK4GvS1AaIIHTfKP44cvEuOBFGbp/view?usp=sharing) [ [Slides source] ](https://drive.google.com/file/d/1nvsj8x_M4dB2DANriSm1Ex_LuIJwNOKt/view?usp=sharing) [ [Notes 1] ](https://drive.google.com/file/d/182zelaJ_Fqp__gxCY6PNVHU0r0LH1KH5/view?usp=sharing) [ [Notes 2] ](https://drive.google.com/file/d/1NJxD0wM2KTYcNVIFeWVe9LpMjZl2ob0e/view?usp=sharing) 
